export const FETCH_PROJECT = "FETCH_PROJECT";
export const FETCH_PROJECT_SUCCESSFUL = "FETCH_PROJECT_SUCCESSFUL";
export const FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED";

export const FETCH_DP = "FETCH_DP";
export const FETCH_DP_SUCCESSFUL = "FETCH_DP_SUCCESSFUL";
export const FETCH_DP_FAILED = "FETCH_DP_FAILED";


export const FETCH_SUB_PROJECT = "FETCH_SUB_PROJECT";
export const FETCH_SUB_PROJECT_SUCCESSFUL = "FETCH_SUB_PROJECT_SUCCESSFUL";
export const FETCH_SUB_PROJECT_FAILED = "FETCH_SUB_PROJECT_FAILED";


export const FETCH_DP_AREAS = "FETCH_DP_AREAS";
export const FETCH_DP_AREAS_SUCCESSFUL = "FETCH_DP_AREAS_SUCCESSFUL";
export const FETCH_DP_AREAS_FAILED = "FETCH_DP_AREAS_FAILED";


export const FETCH_DP_PICTURE = "FETCH_DP_PICTURE";
export const FETCH_DP_PICTURE_SUCCESSFUL = "FETCH_DP_PICTURE_SUCCESSFUL";
export const FETCH_DP_PICTURE_FAILED = "FETCH_DP_PICTURE_FAILED";


export const FETCH_ALL_DP_PICTURES = "FETCH_ALL_DP_PICTURES";
export const FETCH_ALL_DP_PICTURES_SUCCESSFUL = "FETCH_ALL_DP_PICTURES_SUCCESSFUL";
export const FETCH_ALL_DP_PICTURES_FAILED = "FETCH_ALL_DP_PICTURES_FAILED";


export const DELETE_DP_AREA = "DELETE_DP_AREA";
export const DELETE_DP_AREA_SUCCESSFUL = "DELETE_DP_AREA_SUCCESSFUL";
export const DELETE_DP_AREA_FAILED = "DELETE_DP_AREA_FAILED";