// These constants are for the authentication
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESSFUL = "REQUEST_LOGIN_SUCCESSFUL";
export const REQUEST_LOGIN_FAILED = "REQUEST_LOGIN_FAILED";


export const GET_USER_PROFILE ="GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESSFUL ="GET_USER_PROFILE_SUCCESSFUL";
export const GET_USER_PROFILE_FAILED ="GET_USER_PROFILE_FAILED";