name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Setting environment variable from GitHub Secrets
      - name: Set REACT_APP_BASE_URL from GitHub Secrets
        run: echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> $GITHUB_ENV
      - name: Set Environment Variables from .env
        run: |
          cat .env | while read line; do
            if [[ $line != \#* ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done

      - name: Install and Build
        run: |
          npm ci
          npm run build
        env:
          CI: false
      - name: List directories
        run: |
          ls -al
          ls -al build/

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
