name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting environment variable from .env
      - name: Set Environment Variables from .env
        run: |
          cat .env | while read line; do
            if [[ $line != \#* ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch REACT_APP_BASE_URL from Secrets Manager
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id REACT_APP_BASE_URL | jq -r .SecretString)
          REACT_APP_BASE_URL=$(echo $SECRET | jq -r .REACT_APP_BASE_URL)
          echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> $GITHUB_ENV
          echo "Fetched REACT_APP_BASE_URL: $REACT_APP_BASE_URL"  # This line will echo the value

      - name: Install and Build
        run: |
          npm ci
          npm run build
        env:
          CI: false

      - name: List directories
        run: |
          ls -al
          ls -al build/

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
